/* AUTO-GENERATED by scripts/build-sw.mjs — do not edit */
const CACHE_PREFIX = 'np-static-';
const CACHE_NAME = "np-static-2d50b5f1";
const PRECACHE = [
  {
    "url": "/assets/fonts/material-symbols-subset.woff2",
    "revision": "a1755c94"
  },
  {
    "url": "/assets/images/icon.svg",
    "revision": "8fd7be16"
  },
  {
    "url": "/assets/images/icon-16.png",
    "revision": "25fdef6b"
  },
  {
    "url": "/assets/images/icon-32.png",
    "revision": "aadc028a"
  },
  {
    "url": "/assets/images/apple-touch-icon.png",
    "revision": "3ddc3628"
  },
  {
    "url": "/assets/images/icon-192.png",
    "revision": "fb2e0b12"
  },
  {
    "url": "/assets/images/icon-512.png",
    "revision": "5d10a5e2"
  },
  {
    "url": "/assets/images/icon-512-maskable.png",
    "revision": "30880098"
  }
];
const REVISIONS = {
  "/assets/fonts/material-symbols-subset.woff2": "a1755c94",
  "/assets/images/apple-touch-icon.png": "3ddc3628",
  "/assets/images/hero-1280.webp": "abddc903",
  "/assets/images/hero-640.webp": "ac50f8e3",
  "/assets/images/hero-960.webp": "a71d60e2",
  "/assets/images/hero.webp": "61490064",
  "/assets/images/icon-16.png": "25fdef6b",
  "/assets/images/icon-192.png": "fb2e0b12",
  "/assets/images/icon-32.png": "aadc028a",
  "/assets/images/icon-512-maskable.png": "30880098",
  "/assets/images/icon-512.png": "5d10a5e2",
  "/assets/images/icon.svg": "8fd7be16",
  "/assets/images/portfolio/adroll/adroll_1.webp": "3e57d1ff",
  "/assets/images/portfolio/adroll/adroll_2.webp": "cab9c265",
  "/assets/images/portfolio/adroll/adroll_3.webp": "b7e0bcf5",
  "/assets/images/portfolio/adroll/adroll_4.webp": "9f1440f8",
  "/assets/images/portfolio/adroll/adroll_5.webp": "5c90eb9b",
  "/assets/images/portfolio/adroll/adroll_6.webp": "2c137bd4",
  "/assets/images/portfolio/adroll/adroll_7.webp": "3a117fa6",
  "/assets/images/portfolio/adroll/adroll_8.webp": "725a1157",
  "/assets/images/portfolio/dexnews/dexnews_1.webp": "e93d10da",
  "/assets/images/portfolio/dexnews/dexnews_2.webp": "5cc7cae3",
  "/assets/images/portfolio/dexnews/dexnews_3.webp": "df2c25fe",
  "/assets/images/portfolio/dexnews/dexnews_4.webp": "12a1b485",
  "/assets/images/portfolio/dexnews/dexnews_5.webp": "8dd91209",
  "/assets/images/portfolio/dexnews/dexnews_6.webp": "bde511c2",
  "/assets/images/portfolio/dexnews/dexnews_7.webp": "8f3f6e16",
  "/assets/images/portfolio/reset_arcade/reset_arcade_1.webp": "6378cd5a",
  "/assets/images/portfolio/reset_arcade/reset_arcade_2.webp": "998db061",
  "/assets/images/portfolio/reset_arcade/reset_arcade_3.webp": "bd06913e",
  "/assets/images/portfolio/reset_arcade/reset_arcade_4.webp": "96620c79",
  "/assets/images/portfolio/samu_app/samu_app_1.webp": "3f036836",
  "/assets/images/portfolio/samu_app/samu_app_2.webp": "3fba0d76",
  "/assets/images/portfolio/samu_app/samu_app_3.webp": "64e5b43f",
  "/assets/images/portfolio/samu_app/samu_app_4.webp": "44c60331",
  "/assets/images/portfolio/samu_app/samu_app_5.webp": "16e1c308"
};

function revisionKey(pathname, revision) {
  return pathname + '?rev=' + revision;
}

async function cacheFirstLocal(request) {
  const pathname = new URL(request.url).pathname;
  const revision = REVISIONS[pathname];
  if (!revision) {
    return fetch(request);
  }
  const key = revisionKey(pathname, revision);
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key);
  if (cached) {
    return cached;
  }
  const response = await fetch(request);
  if (response.ok) {
    await cache.put(key, response.clone());
  }
  return response;
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) {
    return cached;
  }
  const response = await fetch(request);
  if (response.ok || response.type === 'opaque') {
    await cache.put(request, response.clone());
  }
  return response;
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    if (response.ok) {
      await cache.put(request, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await cache.match(request);
    if (cached) {
      return cached;
    }
    throw error;
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await Promise.all(
        PRECACHE.map(async (entry) => {
          const response = await fetch(entry.url, { cache: 'reload' });
          if (!response.ok) {
            throw new Error('Failed to precache ' + entry.url);
          }
          await cache.put(
            revisionKey(new URL(entry.url, self.location.origin).pathname, entry.revision),
            response,
          );
        }),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
          .map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') {
    return;
  }
  const url = new URL(event.request.url);
  if (url.origin === self.location.origin) {
    if (REVISIONS[url.pathname]) {
      event.respondWith(cacheFirstLocal(event.request));
    }
    return;
  }
  if (url.hostname === 'fonts.gstatic.com') {
    event.respondWith(cacheFirst(event.request));
    return;
  }
  if (url.hostname === 'fonts.googleapis.com') {
    event.respondWith(networkFirst(event.request));
  }
});
