#!/usr/bin/env -S deno run -A

import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  aggregateRevision,
  collectFiles,
  fileRevision,
  themeAssetPath,
} from './theme-asset-hash.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const assetsDir = join(root, 'content/themes/neon-protocol/assets');
const imagesDir = themeAssetPath(root, 'images');
const cssPath = themeAssetPath(root, 'css/screen.css');
const swPath = join(root, 'content/themes/neon-protocol/sw.js');

const PRECACHE_RELATIVE = [
  'fonts/material-symbols-subset.woff2',
  'images/icon.svg',
  'images/icon-16.png',
  'images/icon-32.png',
  'images/apple-touch-icon.png',
  'images/icon-192.png',
  'images/icon-512.png',
  'images/icon-512-maskable.png',
];

function toPublicUrl(relativePath) {
  return `/assets/${relativePath.split('\\').join('/')}`;
}

async function hashedEntry(relativePath) {
  const path = themeAssetPath(root, relativePath);
  try {
    await Deno.stat(path);
  } catch {
    throw new Error(`Missing theme asset for service worker: ${relativePath}`);
  }
  return {
    url: toPublicUrl(relativePath),
    revision: await fileRevision(path),
  };
}

async function runtimeEntries() {
  const heroFiles = (await collectFiles(imagesDir, (_path, name) => /^hero.*\.webp$/i.test(name)))
    .map((path) => relative(assetsDir, path))
    .sort();
  const portfolioFiles = (
    await collectFiles(join(imagesDir, 'portfolio'), (path) => path.endsWith('.webp'))
  )
    .map((path) => relative(assetsDir, path))
    .sort();
  return Promise.all(
    [...heroFiles, ...portfolioFiles].map((relativePath) => hashedEntry(relativePath)),
  );
}

function generateWorkerSource({ cacheName, precache, revisions }) {
  return `/* AUTO-GENERATED by scripts/build-sw.mjs — do not edit */
const CACHE_PREFIX = 'np-static-';
const CACHE_NAME = ${JSON.stringify(cacheName)};
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const REVISIONS = ${JSON.stringify(revisions, null, 2)};

function revisionKey(pathname, revision) {
  return pathname + '?rev=' + revision;
}

async function cacheFirstLocal(request) {
  const pathname = new URL(request.url).pathname;
  const revision = REVISIONS[pathname];
  if (!revision) {
    return fetch(request);
  }
  const key = revisionKey(pathname, revision);
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(key);
  if (cached) {
    return cached;
  }
  const response = await fetch(request);
  if (response.ok) {
    await cache.put(key, response.clone());
  }
  return response;
}

async function cacheFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  const cached = await cache.match(request);
  if (cached) {
    return cached;
  }
  const response = await fetch(request);
  if (response.ok || response.type === 'opaque') {
    await cache.put(request, response.clone());
  }
  return response;
}

async function networkFirst(request) {
  const cache = await caches.open(CACHE_NAME);
  try {
    const response = await fetch(request);
    if (response.ok) {
      await cache.put(request, response.clone());
    }
    return response;
  } catch (error) {
    const cached = await cache.match(request);
    if (cached) {
      return cached;
    }
    throw error;
  }
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      await Promise.all(
        PRECACHE.map(async (entry) => {
          const response = await fetch(entry.url, { cache: 'reload' });
          if (!response.ok) {
            throw new Error('Failed to precache ' + entry.url);
          }
          await cache.put(
            revisionKey(new URL(entry.url, self.location.origin).pathname, entry.revision),
            response,
          );
        }),
      );
      await self.skipWaiting();
    })(),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names
          .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
          .map((name) => caches.delete(name)),
      );
      await self.clients.claim();
    })(),
  );
});

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') {
    return;
  }
  const url = new URL(event.request.url);
  if (url.origin === self.location.origin) {
    if (REVISIONS[url.pathname]) {
      event.respondWith(cacheFirstLocal(event.request));
    }
    return;
  }
  if (url.hostname === 'fonts.gstatic.com') {
    event.respondWith(cacheFirst(event.request));
    return;
  }
  if (url.hostname === 'fonts.googleapis.com') {
    event.respondWith(networkFirst(event.request));
  }
});
`;
}

const precache = await Promise.all(
  PRECACHE_RELATIVE.map((relativePath) => hashedEntry(relativePath)),
);
const runtime = await runtimeEntries();
const allEntries = [...precache, ...runtime];
const revisions = Object.fromEntries(
  allEntries
    .slice()
    .sort((a, b) => a.url.localeCompare(b.url))
    .map((entry) => [entry.url, entry.revision]),
);
const cacheId = await aggregateRevision(allEntries);
const cacheName = `np-static-${cacheId}`;

const css = await Deno.readTextFile(cssPath);
const fontRevision = precache.find((entry) =>
  entry.url.endsWith('/material-symbols-subset.woff2'),
)?.revision;
if (!fontRevision) {
  throw new Error('Material Symbols subset font revision is missing');
}
const nextCss = css.replace(
  /material-symbols-subset\.woff2\?v=[^')]+/,
  `material-symbols-subset.woff2?v=${fontRevision}`,
);
if (nextCss === css && !css.includes(`?v=${fontRevision}`)) {
  throw new Error('Could not update Material Symbols cache-bust query in screen.css');
}
await Deno.writeTextFile(cssPath, nextCss);

await Deno.writeTextFile(swPath, generateWorkerSource({ cacheName, precache, revisions }));
console.log(`Wrote sw.js (${cacheName}, ${allEntries.length} hashed assets)`);
